dependencies:
  - nbserverproxy
  - pyviz::param=1.9.0
  - pyviz::pyviz_comms=0.7.2
  - pyviz::datashader
  - bokeh::bokeh
  - pyviz::panel==0.5.1
  - tornado<6
  - pandas==1.3.5
  - matplotlib==3.2.2
  - urllib3==1.24.3
  - seaborn==0.11.2
  - numpy==1.21.5
  - conda-forge::jupyter-panel-proxy


channels:
- pyviz

#packages:
#- jupyter-panel-proxy
